services:
  web:
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: "false"
      DB_CREATE_ALL_ON_STARTUP: "false"
      SEED_ON_STARTUP: "false"
      FAIL_FAST_ON_DB_ERROR: "true"
      TRUSTED_HOSTS: rqdf.co.id,www.rqdf.co.id
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    ports: []

  nginx:
    image: nginx:stable
    container_name: sekolah_nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/rqdf.co.id.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - media_uploads:/app/app/static/uploads/media:ro
    security_opt:
      - no-new-privileges:true

volumes:
  media_uploads:
